global:
  scrape_interval: 15s  # 메트릭 수집 주기

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "node-exporter"
    static_configs:
      - targets: ["node-exporter:9100"]  # node-exporter 컨테이너의 포트를 설정